[phases.install]
cmds = [
  "npm install --workspace=shared --workspace=backend"
]

[phases.build]
cmds = [
  "npm run build --workspace=shared",
  "npm run build --workspace=backend"
]

[start]
cmd = "node backend/dist/index.js"
